# Generated by Django 5.2.7 on 2025-10-04 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('tiempo_preparacion', models.PositiveIntegerField(help_text='Tiempo en minutos')),
                ('instrucciones', models.TextField()),
                ('ingredientes', models.TextField(help_text='Lista de ingredientes, uno por línea')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
