# Generated by Django 5.2.7 on 2025-10-06 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recetas", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="unidad",
            options={"verbose_name": "Unidad", "verbose_name_plural": "Unidades"},
        ),
    ]
