# Generated by Django 5.2.7 on 2025-10-07 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recetas", "0002_alter_unidad_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="receta",
            name="imagen",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
